openapi: 3.1.0
info:
  title: Loyalty v2 Wallet API | Partner Onboarding APIs
  description: |
    This API Specification is meant to be used by external parties using
    the Loyalty Wallet API. These APIs are used to manage members, credit accounts, and transactions.
    It includes endpoints for creating and updating members, credit accounts, and transactions,
    as well as retrieving account and transaction details.
  version: v2
servers:
  - url: https://apigw-wallet-sbx.payconnect.io
    description: Sandbox Environment
  - url: https://apigw-wallet-dev.payconnect.io
    description: Development Environment
tags:
  - name: Transactions Management
    description: |
      Open API Specification for Transactions Management. Used to retrieve transaction details.
  - name: Members Creation
    description: |
      Open API Specification for Member Management. Used to create members.
  - name: Credit Accounts Management
    description: |
      Open API Specification for Credit Account Management. Used to create and update credit accounts.
  - name: Accounts Management
    description: |
      Open API Specification for Account Management. Used to create accounts and manage wallet balances.
  - name: Wallets Management
    description: |
      Open API Specification for Wallet Management. Used to manage wallet balances and transactions.
security:
  - JWT_token: []
  - api_key: []
paths:
  /api/v1/member:
    post:
      tags:
        - Members Creation
      summary: Create a member by passing a MemberRequest body.
      description: |
        This API endpoint is intended for external parties integrating with the loyalty wallet member 
        functionality. It allows them to create a new member in the system.
      operationId: createMember
      requestBody:
        description: the request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MemberRequest'
        required: true
      responses:
        '200':
          description: the response entity
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MemberResponse'
        '400':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/400'
        '404':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/404'
        '406':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/406'
        '409':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/409'
        '500':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/500'
  /api/v1/creditAccount:
    post:
      tags:
        - Credit Accounts Management
      summary: Create a credit account by passing a CreditAccountRequest body.
      description: |
        This API endpoint is intended for external parties integrating with the loyalty wallet credit 
        account functionality. It allows them to create a new credit account in the system.
      operationId: createCreditAccount
      requestBody:
        description: the request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreditAccountRequest'
        required: true
      responses:
        '200':
          description: Successful Operation
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CreditAccountResponse'
        '400':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/400'
        '404':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/404'
        '406':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/406'
        '409':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/409'
        '500':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/500'
  /api/v1/account:
    post:
      tags:
        - Accounts Management
      summary: Create an account by passing an AccountRequest body.
      description: |
        This API endpoint is intended for external parties integrating with the loyalty wallet account 
        functionality. It allows them to create a new account in the system.
      operationId: createAccount
      requestBody:
        description: the request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountRequest'
        required: true
      responses:
        '200':
          description: Successful Operation
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AccountResponse'
        '400':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/400'
        '404':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/404'
        '406':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/406'
        '409':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/409'
        '500':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/500'
  /api/v1/wallet/deposit/{id}:
    patch:
      tags:
        - Wallets Management
      summary: Add wallet balance to an account by using its ID.
      description: |
        This API endpoint is intended for external parties integrating with the loyalty wallet account 
        functionality. It allows them to add a balance to an existing account in the system.
      operationId: addWalletBalanceByAccountId
      parameters:
        - name: id
          in: path
          description: the id
          required: true
          schema:
            type: integer
            format: int64
        - name: amount
          in: query
          description: the amount
          required: false
          schema:
            type: number
            default: 0
      responses:
        '200':
          description: Successful Operation
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AccountResponse'
        '400':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/400'
        '404':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/404'
        '406':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/406'
        '409':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/409'
        '500':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/500'
  /api/v1/creditAccount/{id}:
    get:
      tags:
        - Credit Accounts Management
      summary: Get a specific credit account by using its ID.
      description: |
        This API endpoint is intended for external parties integrating with the loyalty wallet credit
        account functionality. It allows them to retrieve a credit account by its ID.
      operationId: getCreditAccountById
      parameters:
        - name: id
          in: path
          description: the id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful Operation
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CreditAccountDetailsResponse'
        '400':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/400'
        '404':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/404'
        '406':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/406'
        '409':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/409'
        '500':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/500'
    # patch:
    #   tags:
    #     - Credit Accounts Management
    #   summary: Update credit account response entity.
    #   description: Update credit account response entity.
    #   operationId: updateCreditAccount
    #   parameters:
    #     - name: id
    #       in: path
    #       description: the id
    #       required: true
    #       schema:
    #         type: integer
    #         format: int64
    #   requestBody:
    #     description: the request
    #     content:
    #       application/json:
    #         schema:
    #           $ref: '#/components/schemas/CreditAccountRequest'
    #     required: true
    #   responses:
    #     '200':
    #       description: Successful Operation
    #       content:
    #         '*/*':
    #           schema:
    #             $ref: '#/components/schemas/CreditAccountResponse'
    #     '400':
    #       $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/400'
    #     '404':
    #       $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/404'
    #     '406':
    #       $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/406'
    #     '409':
    #       $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/409'
    #     '500':
    #       $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/500'
  /api/v1/account/wallet/{id}:
    patch:
      tags:
        - Accounts Management
      summary: Add wallet balance to an account by using its ID.
      description: |
        This API endpoint is intended for external parties integrating with the loyalty wallet account 
        functionality. It allows them to add a balance to an existing account in the system.
      operationId: addWalletBalanceByAccountId_1
      parameters:
        - name: id
          in: path
          description: the id
          required: true
          schema:
            type: integer
            format: int64
        - name: amount
          in: query
          description: the amount
          required: false
          schema:
            type: number
            default: 0
      responses:
        '200':
          description: Successful Operation
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AccountResponse'
        '400':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/400'
        '404':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/404'
        '406':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/406'
        '409':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/409'
        '500':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/500'
  /api/v1/wallet/account/{id}:
    get:
      tags:
        - Wallets Management
      summary: Get wallet balance of an account by using its ID.
      description: |
        This API endpoint is intended for external parties integrating with the loyalty wallet account 
        functionality. It allows them to retrieve the wallet balance of an existing account in the system.
      operationId: getWalletBalanceByAccountId
      parameters:
        - name: id
          in: path
          description: the id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful Operation
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WalletResponse'
        '400':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/400'
        '404':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/404'
        '406':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/406'
        '409':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/409'
        '500':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/500'
  /api/v1/transaction/{id}:
    get:
      tags:
        - Transactions Management
      summary: Get a transaction by using its ID.
      description: |
        This API endpoint is intended for external parties integrating with the loyalty wallet transaction 
        functionality. It allows them to retrieve transactions in the system.
      operationId: getTransactionById
      parameters:
        - name: id
          in: path
          description: the id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful Operation
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TransactionResponse'
        '400':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/400'
        '404':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/404'
        '406':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/406'
        '409':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/409'
        '500':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/500'
  /api/v1/transaction/account/{id}:
    get:
      tags:
        - Transactions Management
      summary: Get transactions of an account by using its ID.
      description: |
        This API endpoint is intended for external parties integrating with the loyalty wallet transaction 
        functionality. It allows them to retrieve previous transactions of an account in the system.
      operationId: getAccountTransactionsById
      parameters:
        - name: id
          in: path
          description: the id
          required: true
          schema:
            type: integer
            format: int64
        - name: transactionType
          in: query
          description: the transaction type
          required: false
          schema:
            type: string
        - name: dateFrom
          in: query
          description: the date from
          required: false
          schema:
            type: string
        - name: dateThru
          in: query
          description: the date thru
          required: false
          schema:
            type: string
        - name: pageable
          in: query
          description: the pageable
          required: true
          schema:
            $ref: '../components/utils/Pageable.yaml#/Pageable'
      responses:
        '200':
          description: Successful Operation
          content:
            '*/*':
              schema:
                $ref: '../components/utils/PagedModel.yaml#/PagedModel'
        '400':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/400'
        '404':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/404'
        '406':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/406'
        '409':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/409'
        '500':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/500'
  # /api/v1/creditAccount/search:
  #   get:
  #     tags:
  #       - Credit Accounts Management
  #     summary: Get all credit accounts by.
  #     description: Get all credit accounts by.
  #     operationId: getAllCreditAccountsBy
  #     parameters:
  #       - name: organizationId
  #         in: query
  #         description: the organization id
  #         required: true
  #         schema:
  #           type: integer
  #           format: int64
  #       - name: contactNumber
  #         in: query
  #         description: the contact number
  #         required: false
  #         schema:
  #           type: string
  #       - name: status
  #         in: query
  #         description: the statuses
  #         required: false
  #         schema:
  #           type: array
  #           items:
  #             type: string
  #       - name: dateFrom
  #         in: query
  #         description: the date from
  #         required: false
  #         schema:
  #           type: string
  #       - name: dateThru
  #         in: query
  #         description: the date thru
  #         required: false
  #         schema:
  #           type: string
  #       - name: accountType
  #         in: query
  #         description: the account types
  #         required: false
  #         schema:
  #           type: array
  #           items:
  #             type: string
  #       - name: pageable
  #         in: query
  #         description: the pageable
  #         required: true
  #         schema:
  #           $ref: '../components/utils/Pageable.yaml#/Pageable'
  #     responses:
  #       '200':
  #         description: Successful Operation
  #         content:
  #           '*/*':
  #             schema:
  #               $ref: '../components/utils/PagedModel.yaml#/PagedModel'
  #       '400':
  #         $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/400'
  #       '404':
  #         $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/404'
  #       '406':
  #         $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/406'
  #       '409':
  #         $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/409'
  #       '500':
  #         $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/500'
components:
  securitySchemes:
    JWT_token:
      type: http
      scheme: bearer
      bearerFormat: JWT
    api_key:
      type: apiKey
      in: header
      name: apikey
  schemas:
    MemberRequest:
      $ref: '../components/request/MemberRequest.yaml#/MemberRequest'
    MemberResponse:
      $ref: '../components/response/MemberResponse.yaml#/MemberResponse'
    CreditAccountRequest:
      $ref: '../components/request/CreditAccountRequest.yaml#/CreditAccountRequest'
    AccountResponse:
      $ref: '../components/response/AccountResponse.yaml#/AccountResponse'
    CreditAccountResponse:
      $ref: '../components/response/CreditAccountResponse.yaml#/CreditAccountResponse'
    AccountRequest:
      $ref: '../components/request/AccountRequest.yaml#/AccountRequest'
    WalletResponse:
      $ref: '../components/response/WalletResponse.yaml#/WalletResponse'
    TransactionResponse:
      $ref: '../components/response/TransactionResponse.yaml#/TransactionResponse'
    CreditAccountDetailsResponse:
      $ref: '../components/response/CreditAccountDetailsResponse.yaml#/CreditAccountDetailsResponse'
    ErrorResponse:
      $ref: '../components/response/ErrorResponse.yaml#/ErrorResponse'