openapi: 3.1.0
info:
  title: Loyalty v2 Wallet API | Partner Onboarding APIs
  description: |
    This API Specification is meant to be used by external parties using
    the Loyalty Wallet API. These APIs are used to manage members, credit accounts, and transactions.
    It includes endpoints for creating and updating members, credit accounts, and transactions,
    as well as retrieving account and transaction details.
  version: v2
servers:
  - url: https://apigw-wallet-sbx.payconnect.io
    description: Sandbox Environment
  - url: https://apigw-wallet-dev.payconnect.io
    description: Development Environment
  
tags:
  - name: transaction-controller
    description: The type Transaction controller.
  - name: member-controller
    description: The type Member controller.
  - name: credit-account-controller
    description: The type Credit account controller.
  - name: account-controller
    description: The type Account controller.
  - name: wallet-controller
    description: The type Wallet controller.

security:
  - bearerAuth: []
  - api_key: []

paths:
  /api/v1/member:
    post:
      tags:
        - member-controller
      summary: Create member response entity.
      description: Create member response entity.
      operationId: createMember
      requestBody:
        description: the request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MemberRequest'
        required: true
      responses:
        '200':
          description: the response entity
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MemberResponse'
        '400':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/400'
        '404':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/404'
        '406':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/406'
        '409':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/409'
        '500':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/500'
  /api/v1/creditAccount:
    post:
      tags:
        - credit-account-controller
      summary: Create credit account response entity.
      description: Create credit account response entity.
      operationId: createCreditAccount
      requestBody:
        description: the request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreditAccountRequest'
        required: true
      responses:
        '200':
          description: the response entity
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CreditAccountResponse'
        '400':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/400'
        '404':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/404'
        '406':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/406'
        '409':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/409'
        '500':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/500'
  /api/v1/account:
    post:
      tags:
        - account-controller
      summary: Create account response entity.
      description: Create account response entity.
      operationId: createAccount
      requestBody:
        description: the request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountRequest'
        required: true
      responses:
        '200':
          description: the response entity
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AccountResponse'
        '400':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/400'
        '404':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/404'
        '406':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/406'
        '409':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/409'
        '500':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/500'
  /api/v1/wallet/deposit/{id}:
    patch:
      tags:
        - wallet-controller
      summary: Add wallet balance by account id response entity.
      description: Add wallet balance by account id response entity.
      operationId: addWalletBalanceByAccountId
      parameters:
        - name: id
          in: path
          description: the id
          required: true
          schema:
            type: integer
            format: int64
        - name: amount
          in: query
          description: the amount
          required: false
          schema:
            type: number
            default: 0
      responses:
        '200':
          description: the response entity
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AccountResponse'
        '400':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/400'
        '404':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/404'
        '406':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/406'
        '409':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/409'
        '500':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/500'
  /api/v1/creditAccount/{id}:
    get:
      tags:
        - credit-account-controller
      summary: Gets credit account by id.
      description: Gets credit account by id.
      operationId: getCreditAccountById
      parameters:
        - name: id
          in: path
          description: the id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: the credit account by id
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CreditAccountDetailsResponse'
        '400':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/400'
        '404':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/404'
        '406':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/406'
        '409':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/409'
        '500':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/500'
    patch:
      tags:
        - credit-account-controller
      summary: Update credit account response entity.
      description: Update credit account response entity.
      operationId: updateCreditAccount
      parameters:
        - name: id
          in: path
          description: the id
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: the request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreditAccountRequest'
        required: true
      responses:
        '200':
          description: the response entity
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CreditAccountResponse'
        '400':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/400'
        '404':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/404'
        '406':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/406'
        '409':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/409'
        '500':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/500'
  /api/v1/account/wallet/{id}:
    patch:
      tags:
        - account-controller
      summary: Add wallet balance by account id response entity.
      description: Add wallet balance by account id response entity.
      operationId: addWalletBalanceByAccountId_1
      parameters:
        - name: id
          in: path
          description: the id
          required: true
          schema:
            type: integer
            format: int64
        - name: amount
          in: query
          description: the amount
          required: false
          schema:
            type: number
            default: 0
      responses:
        '200':
          description: the response entity
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AccountResponse'
        '400':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/400'
        '404':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/404'
        '406':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/406'
        '409':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/409'
        '500':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/500'
  /api/v1/wallet/account/{id}:
    get:
      tags:
        - wallet-controller
      summary: Gets wallet balance by account id.
      description: Gets wallet balance by account id.
      operationId: getWalletBalanceByAccountId
      parameters:
        - name: id
          in: path
          description: the id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: the wallet balance by account id
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WalletResponse'
        '400':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/400'
        '404':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/404'
        '406':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/406'
        '409':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/409'
        '500':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/500'
  /api/v1/transaction/{id}:
    get:
      tags:
        - transaction-controller
      summary: Gets transaction by id.
      description: Gets transaction by id.
      operationId: getTransactionById
      parameters:
        - name: id
          in: path
          description: the id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: the transaction by id
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TransactionResponse'
        '400':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/400'
        '404':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/404'
        '406':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/406'
        '409':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/409'
        '500':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/500'
  /api/v1/transaction/account/{id}:
    get:
      tags:
        - transaction-controller
      summary: Gets account transactions by id.
      description: Gets account transactions by id.
      operationId: getAccountTransactionsById
      parameters:
        - name: id
          in: path
          description: the id
          required: true
          schema:
            type: integer
            format: int64
        - name: transactionType
          in: query
          description: the transaction type
          required: false
          schema:
            type: string
        - name: dateFrom
          in: query
          description: the date from
          required: false
          schema:
            type: string
        - name: dateThru
          in: query
          description: the date thru
          required: false
          schema:
            type: string
        - name: pageable
          in: query
          description: the pageable
          required: true
          schema:
            $ref: '../components/utils/Pageable.yaml#/Pageable'
      responses:
        '200':
          description: the account transactions by id
          content:
            '*/*':
              schema:
                $ref: '../components/utils/PagedModel.yaml#/PagedModel'
        '400':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/400'
        '404':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/404'
        '406':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/406'
        '409':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/409'
        '500':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/500'
  /api/v1/creditAccount/search:
    get:
      tags:
        - credit-account-controller
      summary: Gets all credit accounts by.
      description: Gets all credit accounts by.
      operationId: getAllCreditAccountsBy
      parameters:
        - name: organizationId
          in: query
          description: the organization id
          required: true
          schema:
            type: integer
            format: int64
        - name: contactNumber
          in: query
          description: the contact number
          required: false
          schema:
            type: string
        - name: status
          in: query
          description: the statuses
          required: false
          schema:
            type: array
            items:
              type: string
        - name: dateFrom
          in: query
          description: the date from
          required: false
          schema:
            type: string
        - name: dateThru
          in: query
          description: the date thru
          required: false
          schema:
            type: string
        - name: accountType
          in: query
          description: the account types
          required: false
          schema:
            type: array
            items:
              type: string
        - name: pageable
          in: query
          description: the pageable
          required: true
          schema:
            $ref: '../components/utils/Pageable.yaml#/Pageable'
      responses:
        '200':
          description: the all credit accounts by
          content:
            '*/*':
              schema:
                $ref: '../components/utils/PagedModel.yaml#/PagedModel'
        '400':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/400'
        '404':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/404'
        '406':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/406'
        '409':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/409'
        '500':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/500'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    api_key:
      type: apiKey
      in: header
      name: apikey
  schemas:
    MemberRequest:
      $ref: '../components/request/MemberRequest.yaml#/MemberRequest'
    MemberResponse:
      $ref: '../components/response/MemberResponse.yaml#/MemberResponse'
    CreditAccountRequest:
      $ref: '../components/request/CreditAccountRequest.yaml#/CreditAccountRequest'
    AccountResponse:
      $ref: '../components/response/AccountResponse.yaml#/AccountResponse'
    CreditAccountResponse:
      $ref: '../components/response/CreditAccountResponse.yaml#/CreditAccountResponse'
    AccountRequest:
      $ref: '../components/request/AccountRequest.yaml#/AccountRequest'
    WalletResponse:
      $ref: '../components/response/WalletResponse.yaml#/WalletResponse'
    TransactionResponse:
      $ref: '../components/response/TransactionResponse.yaml#/TransactionResponse'
    CreditAccountDetailsResponse:
      $ref: '../components/response/CreditAccountDetailsResponse.yaml#/CreditAccountDetailsResponse'
    ErrorResponse:
      $ref: '../components/response/ErrorResponse.yaml#/ErrorResponse'