openapi: 3.1.0
info:
  title: Loyalty v2 Wallet API | Voucher APIs
  description: |
    This API Specification is meant to be used by external parties using
    the Loyalty Wallet API. It includes endpoints for voucher activation and redemption.
  version: v2
servers:
  - url: https://apigw-wallet-sbx.payconnect.io
    description: Sandbox Environment
  - url: https://apigw-wallet-dev.payconnect.io
    description: Development Environment
  - url: https://apigw-wallet-test.payconnect.io
    description: Test Environment
  - url: https://apigw-wallet-test.payconnect.io
    description: Test Environment
tags:
  - name: Voucher Activation / Redemption
    description: |
      OpenAPI Specification for Voucher Activation / Redemption
security:
  - JWT_token: []
  - api_key: []
paths:
  /api/v1/voucher/redeem:
    post:
      tags:
        - Voucher Activation / Redemption
      summary: Redeem voucher by passing a VoucherEventRequest body.
      description: |
        This API endpoint is intended for external parties integrating with the loyalty wallet voucher 
        functionality. It allows them to redeem a voucher code for their customers or clients.
      operationId: redeemVoucherCode
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoucherEventRequest'
        required: true
      responses:
        '200':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/200'
        '400':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/400'
        '401':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/401'
        '404':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/404'
        '406':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/406'
        '409':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/409'
        '500':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/500'
  /api/v1/voucher/activate/{id}:
    patch:
      tags:
        - Voucher Activation / Redemption
      summary: Activate voucher by passing its ID.
      description: |
        This API endpoint is intended for external parties integrating with the loyalty wallet voucher 
        functionality. It allows them to activate a shared voucher code for their customers or clients.
      operationId: activateVoucherCode
      parameters:
        - name: id
          in: path
          description: the id
          required: true
          schema:
            type: integer
            format: int64
          example: 100
      responses:
        '200':
          description: Successful Operation
          content:
            '*/*':
              schema:
                $ref: '../components/response/VoucherCodeResponse.yaml#/VoucherCodeResponse'
        '400':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/400'
        '404':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/404'
        '406':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/406'
        '409':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/409'
        '500':
          $ref: '../components/response/wallet-v2-voucher-be-response.yaml#/500'
components:
  securitySchemes:
    JWT_token:
      type: http
      scheme: bearer
      bearerFormat: JWT
    api_key:
      type: apiKey
      in: header
      name: apikey
  schemas:
    VoucherEventRequest:
      $ref: '../components/request/VoucherEventRequest.yaml#/VoucherEventRequest'
    VoucherCodeResponse:
      $ref: '../components/response/VoucherCodeResponse.yaml#/VoucherCodeResponse'
    ErrorResponse:
      $ref: '../components/response/ErrorResponse.yaml#/ErrorResponse'